/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imac.dp.view;

import imac.dp.dao.ContratoDao;
import imac.dp.dao.CotistaDao;
import imac.dp.dao.IntegracaoDao;
import imac.dp.dao.ParcelaDao;
import imac.dp.model.Contrato;
import imac.dp.model.Cotista;
import imac.dp.model.Integracao;
import imac.dp.model.Parcela;
import java.awt.Dimension;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suporte-01
 */
public class FrAlertasDP extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrAlertasDP
     */
    public FrAlertasDP() throws ClassNotFoundException {
        initComponents();
        startAlerts();

    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 1, (d.height - this.getSize().height) / 1);
    }

    public void startAlerts() throws ClassNotFoundException {
        listarContratos();
        listarInteVencida();
        listarParcelaVencida();
        listarCotasVencidas();
    }

    public void listarContratos() throws ClassNotFoundException {

        DefaultTableModel modelo = (DefaultTableModel) TbAlertContrato.getModel();
        modelo.setNumRows(0);
        ContratoDao cdao = new ContratoDao();
        Contrato co = new Contrato();
        if (co.getDiasRestantes30dd() <= 0) {

            for (Contrato c : cdao.readContratoAlert()) {
                modelo.addRow(new Object[]{
                    c.getCodContra(),
                    c.getFr_codFuncionario(),
                    c.getFr_nomeFuncionario(),
                    c.getDataAdmiContra(),
                    c.getDataVenc30dd(),
                    (c.getDiasRestantes30dd() * -1),
                    c.getDataVenc90dd(),
                    (c.getDiasRestantes90dd() * -1)
                });
            }

        }

    }

    public void listarInteVencida() throws ClassNotFoundException {

        DefaultTableModel modelo = (DefaultTableModel) TbAlertIntegra.getModel();
        modelo.setNumRows(0);
        IntegracaoDao pdao = new IntegracaoDao();
        Integracao in = new Integracao();
        if (in.getDiasVencidos() <= 0) {
            for (Integracao i : pdao.readIntegracao()) {
                modelo.addRow(new Object[]{
                    i.getCodInt(),
                    i.getFr_codFuncionario(),
                    i.getFr_nomeFuncionario(),
                    i.getFr_nomeEmpresa(),
                    (i.getDiasVencidos() * -1)
                });
            }

        }

    }

    public void listarParcelaVencida() throws ClassNotFoundException {
        ParcelaDao dao = new ParcelaDao();
        DefaultTableModel modelo = (DefaultTableModel) TbAlertParcela.getModel();
        modelo.setNumRows(0);
        DecimalFormat df = new DecimalFormat("R$ ##.##");
        for (Parcela p : dao.readParForStatusNPagaAlert()) {
            modelo.addRow(new Object[]{
                p.getCodParcela(),
                p.getFr_codCop(),
                p.getFr_codFuncionario(),
                p.getFr_nomeFuncionario(),
                df.format(p.getValorParcela()),
                p.getDataVencPar(),
                p.getDiasAtrasoPar() * -1});

        }

    }

    public void listarCotasVencidas() throws ClassNotFoundException {
        DefaultTableModel modelo = (DefaultTableModel) TbAlertaCota.getModel();
        modelo.setNumRows(0);
        CotistaDao pdao = new CotistaDao();

        for (Cotista c : pdao.readCotistaVencidas()) {
            modelo.addRow(new Object[]{
                c.getCodCota(),
                c.getFr_codFuncionario(),
                c.getFr_nomeFuncionario(),
                c.getDataAdmi(),
                c.getDataVenci(),
                (c.getDiasVencidos() * -1)});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbAlertContrato = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbAlertIntegra = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbAlertParcela = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TbAlertaCota = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Alertas Vencimentos - V1.0-20.0813.0");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 51, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbAlertContrato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Contrato", "Cód. Funcionário", "Nome", "Data Admissão", "Data Term. 30d", "Dias para termino", "Data Term. 90d", "Dias para termino"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbAlertContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbAlertContratoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbAlertContrato);
        if (TbAlertContrato.getColumnModel().getColumnCount() > 0) {
            TbAlertContrato.getColumnModel().getColumn(0).setMinWidth(30);
            TbAlertContrato.getColumnModel().getColumn(0).setPreferredWidth(80);
            TbAlertContrato.getColumnModel().getColumn(0).setMaxWidth(100);
            TbAlertContrato.getColumnModel().getColumn(1).setMinWidth(30);
            TbAlertContrato.getColumnModel().getColumn(1).setPreferredWidth(95);
            TbAlertContrato.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 940, 120));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("Listagem de Contratos por vencimento:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, 30));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel2.setText("Listagem de Integrações por vencimento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        TbAlertIntegra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Integra.", "Cód. Funcionário", "Nome Funcionário", "Empresa", "Dias para Vencimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TbAlertIntegra);
        if (TbAlertIntegra.getColumnModel().getColumnCount() > 0) {
            TbAlertIntegra.getColumnModel().getColumn(0).setMinWidth(30);
            TbAlertIntegra.getColumnModel().getColumn(0).setPreferredWidth(80);
            TbAlertIntegra.getColumnModel().getColumn(0).setMaxWidth(90);
            TbAlertIntegra.getColumnModel().getColumn(1).setMinWidth(30);
            TbAlertIntegra.getColumnModel().getColumn(1).setPreferredWidth(95);
            TbAlertIntegra.getColumnModel().getColumn(1).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 940, 120));

        TbAlertParcela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Parcela", "Cód. Coparti.", "Cód. Funcionário", "Nome Funcionário", "Valor da Parcela", "Data Vencimento", "Dias para Vencimento"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(TbAlertParcela);
        if (TbAlertParcela.getColumnModel().getColumnCount() > 0) {
            TbAlertParcela.getColumnModel().getColumn(0).setMinWidth(30);
            TbAlertParcela.getColumnModel().getColumn(0).setPreferredWidth(80);
            TbAlertParcela.getColumnModel().getColumn(0).setMaxWidth(90);
            TbAlertParcela.getColumnModel().getColumn(1).setMinWidth(30);
            TbAlertParcela.getColumnModel().getColumn(1).setPreferredWidth(80);
            TbAlertParcela.getColumnModel().getColumn(1).setMaxWidth(90);
            TbAlertParcela.getColumnModel().getColumn(2).setMinWidth(30);
            TbAlertParcela.getColumnModel().getColumn(2).setPreferredWidth(95);
            TbAlertParcela.getColumnModel().getColumn(2).setMaxWidth(100);
        }

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 940, 130));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel3.setText("Listagem de Cotas Vencidas:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, 30));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        jLabel4.setText("Listagem de Parcelas por vencimento:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, 30));

        TbAlertaCota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Cota", "Cod. Funcionário", "Nome Funcionário", "Data Admissão", "Data Vencimento", "Dias Vencidos"
            }
        ));
        jScrollPane4.setViewportView(TbAlertaCota);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 940, 110));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/update_black.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, -1));

        jTabbedPane1.addTab("Alertas Departamento Pessoal", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 979, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TbAlertContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbAlertContratoMouseClicked

    }//GEN-LAST:event_TbAlertContratoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            startAlerts();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrAlertasDP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbAlertContrato;
    private javax.swing.JTable TbAlertIntegra;
    private javax.swing.JTable TbAlertParcela;
    private javax.swing.JTable TbAlertaCota;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
