/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package imac.dp.view;

import imac.dp.dao.ConnectionFactory;
import imac.dp.dao.UsuarioDao;
import imac.dp.model.Usuario;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author @andre_ments
 */
public class FrMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrMenu
     *
     */
    public String usuarioLogado;

    public FrMenu() throws ClassNotFoundException {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(FrMenu.MAXIMIZED_BOTH);

        URL LocalIcon = getClass().getResource("/img/hs-icon.png");
        Image icone = Toolkit.getDefaultToolkit().getImage(LocalIcon);
        this.setIconImage(icone);

        alertasDP();

    }

    public void alertasDP() throws ClassNotFoundException {

        FrAlertasDP FrAler = null;
        FrAler = new FrAlertasDP();
        desktopPane.add(FrAler);
        FrAler.setVisible(true);
        FrAler.requestFocus();
        FrAler.setPosicao();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator4 = new javax.swing.JSeparator();
        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        CadPro = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentMenuItem = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("System Hardsearch - CONTROLE DPESSOAL - Versão: 1.0-20.0813.0");

        fileMenu.setBorder(null);
        fileMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/register.png"))); // NOI18N
        fileMenu.setMnemonic('f');
        fileMenu.setText("Cadrastrar");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Cadastrar Usuario");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        saveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/funcionario.png"))); // NOI18N
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Cadastrar Funcionário");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);
        fileMenu.add(jSeparator1);

        CadPro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        CadPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/procedimento.png"))); // NOI18N
        CadPro.setMnemonic('y');
        CadPro.setText("Cadastrar Procedimento");
        CadPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadProActionPerformed(evt);
            }
        });
        fileMenu.add(CadPro);
        fileMenu.add(jSeparator5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/company.png"))); // NOI18N
        jMenuItem6.setText("Cadastrar Empresa");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        fileMenu.add(jMenuItem6);
        fileMenu.add(jSeparator2);

        exitMenuItem.setForeground(new java.awt.Color(255, 0, 51));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit_black.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        jMenu1.setBorder(null);
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/coparti.png"))); // NOI18N
        jMenu1.setText("Recursos Humanos");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/controle.png"))); // NOI18N
        jMenuItem1.setText("Controle de Coparticipação");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/integracao.png"))); // NOI18N
        jMenuItem10.setText("Controle de Contratos");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem10);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar.png"))); // NOI18N
        jMenuItem11.setText("Controle de Cotistas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem11);

        menuBar.add(jMenu1);

        helpMenu.setBorder(null);
        helpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/seguranca.png"))); // NOI18N
        helpMenu.setMnemonic('h');
        helpMenu.setText("Seg. Trabalho");

        contentMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/integracao.png"))); // NOI18N
        contentMenuItem.setMnemonic('c');
        contentMenuItem.setText("Controle Integração");
        contentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contentMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(contentMenuItem);

        menuBar.add(helpMenu);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/relatorios.png"))); // NOI18N
        jMenu3.setText("Consultas e Relatórios");

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rela.png"))); // NOI18N
        jMenuItem8.setText("Relat. Parcelas");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem8);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rela.png"))); // NOI18N
        jMenuItem3.setText("Relat. Coparticipações Cadastradas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rela.png"))); // NOI18N
        jMenuItem7.setText("Relatório Razão Pagamento x Arrecadação Coparti.");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/controlepro.png"))); // NOI18N
        jMenuItem2.setText("Listagem de Coparticipações P/Conferência");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);
        jMenu3.add(jSeparator6);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rela.png"))); // NOI18N
        jMenuItem5.setText("Relatório de Integrações Vencidas");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/rela.png"))); // NOI18N
        jMenuItem9.setText("Relatório de Integrações Cadastradas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem9);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/alert.png"))); // NOI18N
        jMenuItem4.setText("Alertas DP");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        menuBar.add(jMenu3);

        jMenu2.setForeground(new java.awt.Color(255, 0, 0));
        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exit_black.png"))); // NOI18N
        jMenu2.setText("Exit");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        int senha = Integer.parseInt(JOptionPane.showInputDialog(null, "Informe senha: ", "ACESSO A CADASTRO, SOMENTE PELO ADMINISTRADOR", JOptionPane.WARNING_MESSAGE));

        if (senha == 123) {
            FrcadUsuario cadU = null;
            cadU = new FrcadUsuario();
            desktopPane.add(cadU);
            cadU.setVisible(true);
            cadU.requestFocus();
        } else {
            JOptionPane.showMessageDialog(null, "Você não tem permissão para executar está ação.\nPor Favor, entrar em contato com o Administrador do sistema.", "ERRO", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_openMenuItemActionPerformed

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        FrcadFuncionario cadF = null;
        cadF = new FrcadFuncionario();
        desktopPane.add(cadF);
        cadF.setVisible(true);
        cadF.requestFocus();
    }//GEN-LAST:event_saveMenuItemActionPerformed

    private void CadProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadProActionPerformed
        FrcadProcedi pro = null;
        pro = new FrcadProcedi();
        desktopPane.add(pro);
        pro.setVisible(true);
        pro.requestFocus();
    }//GEN-LAST:event_CadProActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FrContParticipacao par = null;
        par = new FrContParticipacao();
        desktopPane.add(par);
        par.setVisible(true);
        par.requestFocus();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void contentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contentMenuItemActionPerformed
        FrCadIntegracao Int = null;
        try {
            Int = new FrCadIntegracao();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        desktopPane.add(Int);
        Int.setVisible(true);
    }//GEN-LAST:event_contentMenuItemActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        FrcadEmpresa Emp = null;
        Emp = new FrcadEmpresa();

        desktopPane.add(Emp);
        Emp.setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed


    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        try {

            Connection con = ConnectionFactory.getConnection();
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja emitir o relatório?", "ATENÇÃO", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION) {
                try {

                    JasperPrint print = JasperFillManager.fillReport("\\\\C:\\Hardsearch\\MyReports\\relRazaoPagoNPago.jasper", null, con);
                    JasperViewer.viewReport(print, false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Atenção!\n Nenhum dado encontrado \n\n Código erro: " + e, "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {

            Connection con = ConnectionFactory.getConnection();
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja emitir o relatório de coparticipações cadastradas??", "ATENÇÃO", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION) {
                try {

                    JasperPrint print = JasperFillManager.fillReport("\\\\C:\\Hardsearch\\MyReports\\copartiRel.jasper", null, con);
                    JasperViewer.viewReport(print, false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Atenção!\n Nenhum dado encontrado \n\n Código erro: " + e, "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
                }

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed

        FrRelatorioCopart rel = null;
        rel = new FrRelatorioCopart();
        desktopPane.add(rel);
        rel.setVisible(true);
        rel.requestFocus();
//        try {
//
//            Connection con = ConnectionFactory.getConnection();
//            int confirma = JOptionPane.showConfirmDialog(null, "Atenção!"
//                    + "\nDeseja emitir o relatório de parcelas não pagas?", "Atenção", JOptionPane.YES_NO_OPTION);
//            if (confirma == JOptionPane.YES_OPTION) {
//                try {
//
//                    JasperPrint print = JasperFillManager.fillReport("G:\\Setores\\Administração\\Informática\\Público\\DepartementoPessoal\\MyReports\\relParcelaNPaga.jasper", null, con);
//                    JasperViewer.viewReport(print, false);
//                } catch (Exception e) {
//                    JOptionPane.showMessageDialog(null, "Atenção!\n Nenhum dado encontrado \n\n Código erro: " + e, "Atenção", JOptionPane.YES_OPTION);
//                }
//
//            }
//        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        try {

            Connection con = ConnectionFactory.getConnection();
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja emitir o relatório de coparticipações cadastradas??", "ATENÇÃO", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION) {
                try {

                    JasperPrint print = JasperFillManager.fillReport("\\\\C:\\Hardsearch\\MyReports\\relIntegraVencida.jasper", null, con);
                    JasperViewer.viewReport(print, false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Atenção!\n Nenhum dado encontrado ", "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

                }

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        try {

            Connection con = ConnectionFactory.getConnection();
            int confirma = JOptionPane.showConfirmDialog(null, "Deseja emitir o relatório de coparticipações cadastradas??", "ATENÇÃO", JOptionPane.WARNING_MESSAGE, JOptionPane.YES_NO_OPTION);
            if (confirma == JOptionPane.YES_OPTION) {
                try {

                    JasperPrint print = JasperFillManager.fillReport("\\\\C:\\Hardsearch\\MyReports\\relIntegraCadastradas.jasper", null, con);
                    JasperViewer.viewReport(print, false);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Atenção!\n Nenhum dado encontrado \n\n Código erro: " + e, "ATENÇÃO", JOptionPane.WARNING_MESSAGE);

                }

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        FrContContrato cc = null;
        cc = new FrContContrato();

        desktopPane.add(cc);
        cc.setVisible(true);

    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        FrListarCop co = null;
        co = new FrListarCop();

        desktopPane.add(co);
        co.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        FrContCotista co = null;
        try {
            co = new FrContCotista();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

        desktopPane.add(co);
        co.setVisible(true);

    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        try {
            alertasDP();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrMenu.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        try {
//            UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
//        } catch (Exception e) {
//        };
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrMenu().setVisible(true);

                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FrMenu.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CadPro;
    private javax.swing.JMenuItem contentMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

}
